/* ============================================================
   ShopSphere — data.js
   Product catalogue & category definitions (prices in INR ₹)
   ============================================================ */

const CATEGORIES = [
  { id: 'all',         label: 'All Products' },
  { id: 'electronics', label: 'Electronics'  },
  { id: 'fashion',     label: 'Fashion'       },
  { id: 'home',        label: 'Home & Living' },
  { id: 'sports',      label: 'Sports'        },
  { id: 'beauty',      label: 'Beauty'        },
];

const PRODUCTS = [
  {
    id: 1,
    name: 'AuraWave Pro Headphones',
    category: 'electronics',
    price: 2499,
    originalPrice: 3299,
    rating: 4.8,
    reviews: 2341,
    badge: 'bestseller',
    description: 'Immersive 40-hour playtime with adaptive noise cancellation, spatial audio, and a featherlight titanium frame engineered for all-day comfort.',
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&q=80',
    specs: { Brand: 'AuraWave', Battery: '40 hrs', Connectivity: 'Bluetooth 5.3', Weight: '245g' },
    inStock: true,
  },
  {
    id: 2,
    name: 'LensX Mirrorless Camera',
    category: 'electronics',
    price: 10999,
    originalPrice: 13999,
    rating: 4.9,
    reviews: 876,
    badge: 'new',
    description: 'Full-frame 45MP sensor with dual native ISO and 8-stop in-body stabilisation. Capture professionals-grade imagery in any light.',
    image: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=600&q=80',
    specs: { Sensor: '45MP Full-Frame', ISO: '100–51200', Video: '8K RAW', Weight: '658g' },
    inStock: true,
  },
  {
    id: 3,
    name: 'PulseCore Smartwatch',
    category: 'electronics',
    price: 3299,
    originalPrice: 3999,
    rating: 4.7,
    reviews: 1523,
    badge: 'sale',
    description: 'Advanced health monitoring with ECG, SpO₂, sleep tracking, and a micro-AMOLED always-on display — wrapped in aerospace-grade aluminium.',
    image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&q=80',
    specs: { Display: '1.9″ AMOLED', Battery: '7 days', Sensors: 'ECG, SpO₂, GPS', Rating: 'IP68' },
    inStock: true,
  },
  {
    id: 4,
    name: 'UrbanEdge Leather Jacket',
    category: 'fashion',
    price: 1599,
    originalPrice: 2199,
    rating: 4.6,
    reviews: 431,
    badge: 'sale',
    description: 'Full-grain vegetable-tanned leather with a buttery-soft hand feel. Tailored slim silhouette with gunmetal hardware — built to age beautifully.',
    image: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=600&q=80',
    specs: { Material: 'Full-Grain Leather', Fit: 'Slim', Lining: 'Satin', Care: 'Dry Clean' },
    inStock: true,
  },
  {
    id: 5,
    name: 'Celestia Running Shoes',
    category: 'sports',
    price: 1199,
    originalPrice: 1799,
    rating: 4.5,
    reviews: 3102,
    badge: null,
    description: 'Carbon-fibre plate + responsive foam midsole returns 85% energy for every stride. Breathable flyknit upper keeps you cool through the long run.',
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&q=80',
    specs: { Upper: 'Flyknit', Midsole: 'ReactFoam+', Drop: '8mm', Weight: '265g' },
    inStock: true,
  },
  {
    id: 6,
    name: 'Lumière Skincare Set',
    category: 'beauty',
    price: 799,
    originalPrice: 1199,
    rating: 4.8,
    reviews: 988,
    badge: 'bestseller',
    description: '5-piece K-beauty routine with hyaluronic acid serum, ceramide moisturiser, vitamin-C brightening essence and SPF 50 sunscreen — clinically tested.',
    image: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=600&q=80',
    specs: { Pieces: '5', Skin: 'All Types', Tested: 'Dermatologically', Paraben: 'Free' },
    inStock: true,
  },
  {
    id: 7,
    name: 'Nordic Oak Desk Lamp',
    category: 'home',
    price: 699,
    originalPrice: 999,
    rating: 4.4,
    reviews: 215,
    badge: 'new',
    description: 'Warm-to-cool tunable LED (2700 K–6500 K) with wireless Qi charging base and touch-dimmable stem. Scandinavian oak veneer finish.',
    image: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=600&q=80',
    specs: { Lumens: '800lm', CCT: '2700–6500K', Charging: 'Qi 15W', Material: 'Oak + Aluminium' },
    inStock: true,
  },
  {
    id: 8,
    name: 'VoltSlim Laptop Pro',
    category: 'electronics',
    price: 15499,
    originalPrice: 18999,
    rating: 4.9,
    reviews: 674,
    badge: 'new',
    description: '14″ 2.8K OLED display, 13th Gen processor, 32 GB LPDDR5 RAM, 1 TB NVMe SSD — all in a 1.1 kg magnesium chassis with 22-hour battery life.',
    image: 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=600&q=80',
    specs: { Display: '14″ 2.8K OLED', RAM: '32 GB', Storage: '1 TB NVMe', Weight: '1.1kg' },
    inStock: true,
  },
  {
    id: 9,
    name: 'Summit Trail Backpack',
    category: 'sports',
    price: 999,
    originalPrice: 1499,
    rating: 4.6,
    reviews: 782,
    badge: null,
    description: '40 L capacity with internal frame, integrated rain cover, hydration bladder sleeve and ergonomic ventilated back panel. Ready for any terrain.',
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&q=80',
    specs: { Volume: '40L', Frame: 'Internal', Hydration: '3L Compatible', Rating: 'IPX4' },
    inStock: true,
  },
  {
    id: 10,
    name: 'Velvet Breeze Perfume',
    category: 'beauty',
    price: 1299,
    originalPrice: 1799,
    rating: 4.7,
    reviews: 563,
    badge: 'bestseller',
    description: 'Eau de parfum opening with bergamot and pink pepper, heart of oud and Bulgarian rose, dry-down of white musk and sandalwood. 12-hour longevity.',
    image: 'https://images.unsplash.com/photo-1541643600914-78b084683702?w=600&q=80',
    specs: { Size: '100ml EDP', Notes: 'Oud · Rose · Musk', Longevity: '12 hrs', Origin: 'France' },
    inStock: false,
  },
  {
    id: 11,
    name: 'Linen Throw Blanket',
    category: 'home',
    price: 499,
    originalPrice: 799,
    rating: 4.5,
    reviews: 344,
    badge: 'sale',
    description: 'Stonewashed Belgian linen in 12 curated tones. Naturally thermoregulating — cool in summer, warm in winter. OEKO-TEX® certified.',
    image: 'https://images.unsplash.com/photo-1580301762395-21ce84d00bc6?w=600&q=80',
    specs: { Material: 'Belgian Linen', Size: '130×180cm', Certified: 'OEKO-TEX®', Care: 'Machine Wash' },
    inStock: true,
  },
  {
    id: 12,
    name: 'Apex Polo Shirt',
    category: 'fashion',
    price: 549,
    originalPrice: 799,
    rating: 4.3,
    reviews: 201,
    badge: null,
    description: 'Piqué cotton with moisture-wicking finish — the ideal bridge between smart and athletic. Ribbed collar holds its shape wash after wash.',
    image: 'https://images.unsplash.com/photo-1586790170083-2f9ceadc732d?w=600&q=80',
    specs: { Fabric: '100% Piqué Cotton', Fit: 'Regular', Feature: 'Moisture-Wick', Care: 'Machine Wash' },
    inStock: true,
  },
];